[package]
name = "fermats_kitchen"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fermats_utensil"

[dependencies]
argh = "0.1.12"
fixedbitset = "0.5.6"
rayon = "1.9.0"

[dependencies.rug]
version = "1.22"
default-features = false
features = ["integer", "rand"]
